source "https://rubygems.org"

gem 'jekyll'
gem 'sassc'
gem 'minima'
gem 'jekyll-paginate-v2'
gem 'jekyll-feed'
gem 'jekyll-seo-tag'
gem 'csv'
gem 'base64'
gem 'jekyll-picture-tag'
gem 'kramdown-parser-gfm'
gem 'webrick'
gem 'logger'
gem 'bigdecimal'